# Use Python 3.10 image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files into container
COPY . /app

# Default command to run the Python program
CMD ["python", "main.py"]

